# This is a generated file. Not intended for manual editing.
services:
  evaluation.api:
    build:
      context: "C:\\Users\\danie\\RiderProjects\\Evaluerings-app-FMS"
      dockerfile: "Evaluering.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Evaluering.API.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "evaluation.api:dev"
    ports: []
    volumes:
    - "C:\\Users\\danie\\RiderProjects\\Evaluerings-app-FMS\\Evaluering.API:/app:rw"
    - "C:\\Users\\danie\\RiderProjects\\Evaluerings-app-FMS:/src:rw"
    - "C:\\Users\\danie\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
  reverseproxy.api:
    build:
      context: "C:\\Users\\danie\\RiderProjects\\Evaluerings-app-FMS"
      dockerfile: "ReverseProxy.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/ReverseProxy.API.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "reverseproxy.api:dev"
    ports: []
    volumes:
    - "C:\\Users\\danie\\RiderProjects\\Evaluerings-app-FMS\\ReverseProxy.API:/app:rw"
    - "C:\\Users\\danie\\RiderProjects\\Evaluerings-app-FMS:/src:rw"
    - "C:\\Users\\danie\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
  school.api:
    build:
      context: "C:\\Users\\danie\\RiderProjects\\Evaluerings-app-FMS"
      dockerfile: "School.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/School.API.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "school.api:dev"
    ports: []
    volumes:
    - "C:\\Users\\danie\\RiderProjects\\Evaluerings-app-FMS\\School.API:/app:rw"
    - "C:\\Users\\danie\\RiderProjects\\Evaluerings-app-FMS:/src:rw"
    - "C:\\Users\\danie\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
