services:
  school.api:
    image: school.api
    build:
      context: .
      dockerfile: School.API/Dockerfile
    networks:
      - backend
        
  evaluation.api:
    image: evaluation.api
    build:
      context: .
      dockerfile: Evaluering.API/Dockerfile
    networks:
      - backend
      
  schooldb:
    image: mcr.microsoft.com/mssql/server:latest
    volumes:
      - C:\Dev\SQL\SchoolApp:/var/opt/mssql/data
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "StrongPassword123."
    ports:
      - "8090:1433"
    networks:
      - backend
  
  evaluationdb:
    image: mcr.microsoft.com/mssql/server:latest
    volumes:
      - C:\Dev\SQL\EvaluationApp:/var/opt/mssql/data
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "StrongPassword123."
    ports:
      - "9090:1433"
    networks:
      - backend
        
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
