services:
  school.api:
    image: school.api
    build:
      context: .
      dockerfile: School.API/Dockerfile
    networks:
      - schoolNetwork
  
  schooldb:
    image: mcr.microsoft.com/mssql/server:latest
    volumes:
      - C:\Dev\SQL\SchoolApp:/var/opt/mssql/data
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "StrongPassword123."
    ports:
      - "8090:1433"
    networks:
      - schoolNetwork
  
  reverseproxy.api:
    image: reverseproxy.api
    build:
      context: .
      dockerfile: ReverseProxy.API/Dockerfile
    ports:
      - "9000:9000"
    environment:
      ASPNETCORE_HTTP_PORTS: 9000
    depends_on:
      evaluation.api:
        condition: service_started
    networks:
      - evaluationApiNetwork
  
  evaluation.api:
    image: evaluation.api
    build:
      context: .
      dockerfile: Evaluering.API/Dockerfile
    depends_on:
      evaluationdb:
        condition: service_started
      fakemailserver:
        condition: service_started
    networks:
      - evaluationApiNetwork
      - evaluationDatabaseNetwork
  
  evaluationdb:
    image: mcr.microsoft.com/mssql/server:latest
    volumes:
      - C:\Dev\SQL\EvaluationApp:/var/opt/mssql/data
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "StrongPassword123."
    ports:
      - "9090:1433"
    networks:
      - evaluationDatabaseNetwork
  
  fakemailserver:
    image: reachfive/fake-smtp-server:latest
    ports:
      - "1025:1025"
      - "1080:1080"
    volumes:
      - ./emails:/tmp/fakemail
    networks:
      - evaluationDatabaseNetwork


networks:
  evaluationApiNetwork:
    driver: bridge
  evaluationDatabaseNetwork:
    driver: bridge
  schoolNetwork:
    driver: bridge
