services:
  school.api:
    image: school.api
    build:
      context: .
      dockerfile: School.API/Dockerfile
    networks:
      - evaluationDatabaseNetwork
        
  evaluation.api:
    image: evaluation.api
    build:
      context: .
      dockerfile: Evaluering.API/Dockerfile
    networks:
      - evaluationDatabaseNetwork
      
  schooldb:
    image: mcr.microsoft.com/mssql/server:latest
    volumes:
      - C:\Dev\SQL\SchoolApp:/var/opt/mssql/data
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "StrongPassword123."
    ports:
      - "8090:1433"
    networks:
      - evaluationDatabaseNetwork
  
  evaluationdb:
    image: mcr.microsoft.com/mssql/server:latest
    volumes:
      - C:\Dev\SQL\EvaluationApp:/var/opt/mssql/data
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "StrongPassword123."
    ports:
      - "9090:1433"
    networks:
      - evaluationDatabaseNetwork
      
  fakemailserver:
    image: reachfive/fake-smtp-server:latest
    ports:
      - "1025:1025"
      - "1080:1080"
    volumes:
      - ./emails:/tmp/fakemail
    networks:
      - evaluationDatabaseNetwork
    
        
networks:
  evaluationApiNetwork:
    driver: bridge
  evaluationDatabaseNetwork:
    driver: bridge
