services:
  school.api:
    image: school.api
    build:
      context: .
      dockerfile: School.API/Dockerfile
    networks:
      - backend
      
  db:
    image: mcr.microsoft.com/mssql/server:latest
    volumes:
      - C:\Dev\SQL\Evalueringsapp:/var/opt/mssql/data
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "StrongPassword123."
    ports:
      - "8090:1433"
    networks:
      - backend
        
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

  validation.api:
    image: validation.api
    build:
      context: .
      dockerfile: Validation.API/Dockerfile
